### ISSUE TITLE
add an option to rotate the image 

### ISSUE THREAD

**Issue by qdwang** [qdwang/QuickRawPicker#12]
From @SilvioGrosso,
add an option to rotate the image (even a simple shortcut to rotate 90° would suffice). I take my RAWs pictures on a tripood and a macro rail slider (for focus stacking stuff) and with QuickRawPicker they are all upside down now (180° off). Therefore, it would be great to being able to rotate them :-)

**Comment by qdwang** [comment]
@SilvioGrosso, so a simple 180 rotation will do the work, I guess? 

It much easier to just implement the 180° rotation rather than a 90° rotation, because the width and height won't change for a 180° rotation.

**Comment by qdwang** [comment]
I've added the 180 degree rotation in 0e324ede27ecd237351459d344912a207f94e7df

**Comment by SilvioGrosso** [comment]
Hello qdwang!

> I've added the 180 degree rotation in 0e324ed

Thanks a lot. The shortcut R is indeed useful :-)

**Comment by qdwang** [comment]
https://github.com/qdwang/QuickRawPicker/releases/tag/v0.1.11
The feature has been added to the v0.1.11
