### ISSUE TITLE
zoom on the mouse cursor position

### ISSUE THREAD

**Issue by qdwang** [qdwang/QuickRawPicker#13]
From @SilvioGrosso,

add an option to zoom on the mouse cursor position. At present, the zoom always occurs on the center of the images. With other softwares (Darktable, ART, Gimp, Krita etc) the zoom occurs exactly at the mouse's cursor place on the image (e.g. on the left upper side).

**Comment by qdwang** [comment]
The problem is there will be multiple images on the screen, if the cursor is on one image, which scale position should other images should use(they could have totally different sizes)? @SilivioGrosso

**Comment by SilvioGrosso** [comment]
>  which scale position should other images should use(they could have totally different sizes)?

Yep. With different images, with different size, on the screen it makes indeed sense to apply the zoom on the center of the image. I have just checked on Picasa (a software developed by Google in the past) and it does exactly like this.

My proposal was for one single image. In this scenario you usually want to zoom where your mouse cursor is placed. At least, it is what occurs with Krita, Gimp, Darktable, RawTherapee...
On top of that, even with 2 images with the *same* size you usually want to zoom where the mouse cursors is placed. For instace, I take 2 pictures with different aperture (F8 and F11) and I want to check in one specific part (right, left ecc) of the images which one is better (e.g. the most sharp).

With Picasa when you zoom into an image the zoom is applied on the center of the image. The same as QuickRawPicker. However, a new little window appears (bottom right) and you can move the "rectangle" of the zoom to quickly pan into the image. Most of all, the preview of the zoomed image is quite useful to get an idea of the whole pan to apply to the image.
See this screenshot:
![2021-08-15 png](https://user-images.githubusercontent.com/33007383/129491171-466917fc-e2f3-46e9-a1de-5e54bc3893c1.jpg)

**Comment by SilvioGrosso** [comment]
Hello @qdwang 

Just out of curiosity...
You might want to check how another open source software works with different images in size...
For instance, take a look at:
https://github.com/rbreu/beeref

With this software the zoom is applied exactly where the mouse cursors is placed even though the images are of different size:
![2021-08-15 (1) png](https://user-images.githubusercontent.com/33007383/129492130-71aaf6ab-1148-4bab-b188-9be12a2eed1c.jpg)

**Comment by qdwang** [comment]
@SilvioGrosso Thanks for your info. I've committed the changes, this feature will be deployed in the next version.
