### ISSUE TITLE
xmp file compatible with darktable

### ISSUE THREAD

**Issue by qdwang** [qdwang/QuickRawPicker#16]
naming rule is like pp3, just add .xmp at the end

**Comment by gadolf66** [comment]
Thanks for addressing this.
Just take note that there's a whole philosophical discussion around whether the raw extension should or shouldn't be part of the xmp file, and that other software might expect the format that you are already using. Hence my suggestion of offering the user a choice, somewhere in the settings.

The mentioned (heat) discussion can be seen here: [https://discuss.pixls.us/t/linux-applications-and-their-non-standard-xmp-sidecar-naming-convention/2688?u=gadolf](https://discuss.pixls.us/t/linux-applications-and-their-non-standard-xmp-sidecar-naming-convention/2688?u=gadolf)

**Comment by qdwang** [comment]
I got it. I won't directly change the xmp file naming rules in code, but I'll add an option in settings for this.
