### ISSUE TITLE
Double-click to display an image (feature request)

### ISSUE THREAD

**Issue by SilvioGrosso** [qdwang/QuickRawPicker#18]
Hello qdwang,

Tested on the latest version (0.1.11) on Windows 10

At present, it looks like there is not a shortcut to display an image in the main window
It seems you are  forced to click the underneath button "Compare"
Therefore if you have a long number of images in the stack (thumbnails) you are forced to move up and down with the cursor mouse to press the button "Compare".

I propose to add a shortcut to avoid this moving of the mouse's cursor (up-down). 
For example, by *double-clicking* (like in RawTherapee - Darktable) of the *left  mouse button*.
This is way faster :-)

Best regards!

**Comment by qdwang** [comment]
Actually, you can use hotkey C to compare. So generally one can left click the thumbnail and press C. The photo will be shown.

But still, double clicking to open one photo is also a good way. I'll add this.
