### ISSUE TITLE
Zoom to mouse's cursor (and depending on the image)

### ISSUE THREAD

**Issue by SilvioGrosso** [qdwang/QuickRawPicker#22]
Hello @qdwang

Tested the new version 0.1.12 on Windows 10

Just tested the new zoom option :-)
In all truth I don't know whether it is a "bug" or it is fully intended to work like this.
In short, in my view, as it is implemented now it is hard to get an idea about how the zoom is moving into the image.
With QuickRawPicker there is not a preview window where you take a look at the zoom applied (based on the whole image).

I have tested Gimp and ART (a clone of RawTherapee) and the zoom is applied where the mouse cursor is placed. On top of this the image is *stuck* so that the zoom occurs exactly in the same point.
In the previous version of QuickRawPicker the zoom was applied on the center of the image and it was easier to understand how it occurred.

I have recorded (dropbox link: https://www.dropbox.com/s/1or2alp16d30wl1/ZOOM_MOUSE_CURSOR.mp4?dl=0) a video with Gimp, ART, QuickRawPicker where I apply the zoom on the same image at the mouse cursor position.

This same video also plays well in the github Preview tab (so that you are not forced to download it from dropbox):

https://user-images.githubusercontent.com/33007383/129951267-bdbc0481-dee4-442c-b2d0-5796c18d1983.mp4

Thanks a lot for your software!

**Comment by qdwang** [comment]
[QuickRawPicker-v0.1.12-win-x64-be59e27.zip](https://github.com/qdwang/QuickRawPicker/files/7013192/QuickRawPicker-v0.1.12-win-x64-be59e27.zip)

Really thanks for the video. I've upload a test build, could you try this out to see if this fit your needs?

**Comment by qdwang** [comment]
It seems still a little different from the video above. I'll try another fix.

**Comment by SilvioGrosso** [comment]
Hello @qdwang 

I have tried on Krita 5.0 beta, BeeRef, Picasa. They all work like in the previous video (with GIMP and ART in action):
For instance, here is a video I have recorded with Krita and BeeRef zooming on the cursor position:


https://user-images.githubusercontent.com/33007383/130125947-d16b5253-d304-49bd-9fe4-fde07342f53f.mp4


Other softwares show a little window with a preview of your image currently displayed.
When you zoom a rectangle appears and you can also move this rectangle to pan into the zoomed image.
By way of this preview image (by moving the rectangle) you can correct the zoom if it does not work well enough for your needs.
For instance RawProc (https://github.com/butcherg/rawproc/releases):
![rawproc](https://user-images.githubusercontent.com/33007383/130126081-b98964f5-f96c-4ef7-b779-508e7f522881.jpg)

**Comment by qdwang** [comment]
[QuickRawPicker-v0.1.12-win-x64-a92cfc9.zip](https://github.com/qdwang/QuickRawPicker/files/7019446/QuickRawPicker-v0.1.12-win-x64-a92cfc9.zip)

Hi, could you try this fix pls? This should be the same as the softwares show above.

**Comment by SilvioGrosso** [comment]
Hello @qdwang,

It works great now.
Tested on Windows 10, as usual.

I have tested it also with 2 similar (only the aperture is different in both)  NEFs images together. The zoom is applied correctly on both images :-)
Thanks a lot!
 

    Il venerdì 20 agosto 2021, 07:59:07 CEST, qdwang ***@***.***> ha scritto:  
 
 


QuickRawPicker-v0.1.12-win-x64-a92cfc9.zip

Hi, could you try this fix pls? This should be the same as the softwares show above.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qdwang** [comment]
Great, I'll add this fix in the next release.

**Comment by qdwang** [comment]
Now v0.1.13 release should have this fix.
