### ISSUE TITLE
add flatpak or snap

### ISSUE THREAD

**Issue by anarcat** [qdwang/QuickRawPicker#28]
It would be great if this app was packaged as a flatpak. This would allow you, the developer, to directly ship the app to users without having to wait for distribution to vet and package your program. In turns, for users, flatpaks can provide a little bit of isolation and makes it more comfortable to test applications this way (as opposed to just running the released binary).

Thanks!

**Comment by qdwang** [comment]
Nice idea. I've also checked AppImage. I'll try to pack the next version in these platforms.

**Comment by anarcat** [comment]
> Nice idea. I've also checked AppImage. I'll see if it's easy to pack the next version in these platforms.

from what i remember flatpak is basically an enhanced appimge and i'm not sure it's worth looking into both. i personnally a fan of flatpak over snap, but that's somewhat of a religious issue (e.g. redhat vs canonical).

**Comment by mikae1** [comment]
Came here to make an Issue asking for the same thing. 🙂

> Nice idea. I've also checked AppImage. I'll see if it's easy to pack the next version in these platforms.

I prefer an AppImage because they're stupid simple. That said, it seems Flatpak is gaining ground with the [Manjaro team working on a distro using it instead of pacman](https://forum.manjaro.org/t/trying-to-make-manjaro-more-stable-and-user-friendly/95529/3).

**Comment by qdwang** [comment]
@mikae1 QuickRawPicker for linux is completely portable, so no installation is needed. 
So maybe your needs is just an auto shortcut creation?

**Comment by mikae1** [comment]
Thanks, I see. Shortcuts are not necessary. :)
