### ISSUE TITLE
Segmentation fault when trying to open pictures

### ISSUE THREAD

**Issue by sbij** [qdwang/QuickRawPicker#6]
Hello, thanks for the program, I am on Debian Linux, I downloaded `QuickRawPicker-v0.1.8-X11-x86_64.zip`, unzipped it, then ran `./QuickRawPicker-v0.1.8-X11.x86_64` in console.

It launched but console returned me

```
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL ES Batching: ON
 
ERROR: open_dynamic_library: Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
   At: drivers/unix/os_unix.cpp:415.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:502.
ERROR: init_library: No nativescript_init in "res://Asset/Lib/Bin/QRPBridge.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1482.
```

Then i tried importing pictures, but the program stopped and console returned me `Segmentation fault`

Is there something I am missing? Thank you

**Comment by qdwang** [comment]
This may caused by the `GLIBC_2.29' not found`. Could you run `ldd --version` and paste the output here pls?

**Comment by sbij** [comment]
`ldd --version` outputs `ldd (Debian GLIBC 2.28-10) 2.28`. I'm on Debian Stable, so i may dont have all the latest versions

**Comment by qdwang** [comment]
2.28 is enough. I'll downgrade the glibc version used in QRP.

**Comment by qdwang** [comment]
[QuickRawPicker-glibc_fix.zip](https://github.com/qdwang/QuickRawPicker/files/6910996/QuickRawPicker-glibc_fix.zip)

Could you try this fix build? I've rebuilt the project under ubuntu 16.04 with GLIBC 2.23, and tested it under ubuntu 18.04 and 20.04.

It should work under Debian stable.

Thanks.

**Comment by sbij** [comment]
Thanks, tried that. I get no more error on launch. Console output:

```
Godot Engine v3.3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL ES Batching: ON
```

*But* i still have a Segfault error, but it isn't on every folder. Folder with Nikon .nef (with .pp3 and .xmp files) opens well with no error, but folder with .dng (with .xmp and .jpg in same folder) images crashes with segfault. These .dng were made with CHDK (and can be opened with darktable)

**Comment by qdwang** [comment]
[QuickRawPicker-libz_fix.zip](https://github.com/qdwang/QuickRawPicker/files/6912079/QuickRawPicker-libz_fix.zip)

Thanks for the testing. This may cause by the libz issue for dng file(since QRP will ignore JPG files). 
If this build still failed to run, could you upload one dng that can cause crash?

**Comment by sbij** [comment]
Yes i guess so, and it does make the program crash on my computer with a segfault.

**Comment by qdwang** [comment]
A new version v0.1.10 has been deployed [https://github.com/qdwang/QuickRawPicker/releases](https://github.com/qdwang/QuickRawPicker/releases).

It has tested all the raw files in https://raw.pixls.us/. So it should not crash now.

**Comment by sbij** [comment]
Yes, works well on my side! Thanks
